/** 视图通用文案常量 —— 统一维护入口，避免中文 UI 文案散落在各视图里的硬编码。
 *  UI_TEXT / MODAL_TEXT 的取值均来自 i18n 字典，切换语言时自动返回对应文案。 */

import { t, tArr } from './i18n';

export const UI_TEXT = {
	// 通用动作（映射到 common.*）
	get save() { return t('common.save'); },
	get cancel() { return t('common.cancel'); },
	get edit() { return t('common.edit'); },
	get delete() { return t('common.delete'); },
	get openSource() { return t('common.openSource'); },
	get taskDetail() { return t('common.taskDetail'); },
	get notSet() { return t('common.notSet'); },
	get all() { return t('ui.all'); },
	get today() { return t('ui.today'); },
	get clickDayHint() { return t('ui.clickDayHint'); },
	get noTaskOnDay() { return t('ui.noTaskOnDay'); },
	get newProjectBtn() { return t('ui.newProjectBtn'); },
	get calMonthFmt() { return t('ui.calMonthFmt'); },
	get calWeekdays() { return tArr('ui.calWeekdays'); },
	// 优先级短标签（卡片/列表/看板里的小徽章用）。fallback 在显示层做。
	prioShort(storage: string): string {
		const map: Record<string, string> = {
			'重要且紧急': t('modal.prioUrgentImpShort'),
			'重要不紧急': t('modal.prioImpNotUrgentShort'),
			'紧急不重要': t('modal.prioUrgentNotImpShort'),
			'不重要不紧急': t('modal.prioNotImpNotUrgentShort'),
		};
		return map[storage] ?? storage;
	},
	// 状态短标签（用同一份 modal.st* 翻译；fallback 用 storage value）
	statusLabel(storage: string): string {
		const map: Record<string, string> = {
			'待办': t('modal.stTodo'),
			'进行中': t('modal.stInProgress'),
			'已阻塞': t('modal.stBlocked'),
			'已完成': t('modal.stDone'),
			'已取消': t('modal.stCancelled'),
		};
		return map[storage] ?? storage;
	},
	// 优先级选项长标签（任务编辑弹窗里用，带 emoji）
	prioLong(storage: string): string {
		const map: Record<string, string> = {
			'重要且紧急': t('modal.prioUrgentImp'),
			'重要不紧急': t('modal.prioImpNotUrgent'),
			'紧急不重要': t('modal.prioUrgentNotImp'),
			'不重要不紧急': t('modal.prioNotImpNotUrgent'),
		};
		return map[storage] ?? storage;
	},
	// 优先级纯文本标签（TODO 卡片用，无 emoji；样式参考本周待办的紧急标签 ad-wo__urg）
	prioText(storage: string): string {
		const map: Record<string, string> = {
			'重要且紧急': t('modal.prioUrgentImpText'),
			'重要不紧急': t('modal.prioImpNotUrgentText'),
			'紧急不重要': t('modal.prioUrgentNotImpText'),
			'不重要不紧急': t('modal.prioNotImpNotUrgentText'),
		};
		return map[storage] ?? storage;
	},

	// 项目总览（第二页）
	get filter() { return t('ui.filter'); },
	get noTasks() { return t('ui.noTasks'); },
	get poGantt() { return t('ui.poGantt'); },
	get poList() { return t('ui.poList'); },
	get poCalendar() { return t('ui.poCalendar'); },
	get poKanban() { return t('ui.poKanban'); },
	get poDeps() { return t('ui.poDeps'); },
	get poFiles() { return t('ui.poFiles'); },
	get poStats() { return t('ui.poStats'); },
	get poTaskName() { return t('ui.poTaskName'); },
	get poPriority() { return t('ui.poPriority'); },
	get poStart() { return t('ui.poStart'); },
	get poDue() { return t('ui.poDue'); },
	get poStatus() { return t('ui.poStatus'); },
	get poProject() { return t('ui.poProject'); },

	// 看板（第三页）
	get opAll() { return t('ui.opAll'); },
	get opRoadmap() { return t('ui.opRoadmap'); },
};

/** 弹窗专属文案（映射到 modal.*），切换语言时自动翻译。 */
export const MODAL_TEXT = {
	get taskTitle() { return t('modal.taskTitle'); },
	get taskName() { return t('modal.taskName'); },
	get project() { return t('modal.project'); },
	get parent() { return t('modal.parent'); },
	get noParent() { return t('modal.noParent'); },
	get startDate() { return t('modal.startDate'); },
	get endDate() { return t('modal.endDate'); },
	get noEndDate() { return t('modal.noEndDate'); },
	get priority() { return t('modal.priority'); },
	get status() { return t('modal.status'); },
	get type() { return t('modal.type'); },
	get repeatFreq() { return t('modal.repeatFreq'); },
	get everyNDays() { return t('modal.everyNDays'); },
	get workdaysOnly() { return t('modal.workdaysOnly'); },
	get repeatWeekdays() { return t('modal.repeatWeekdays'); },
	get monthDay() { return t('modal.monthDay'); },
	get reminder() { return t('modal.reminder'); },
	get tags() { return t('modal.tags'); },
	get tagPlaceholder() { return t('modal.tagPlaceholder'); },
	get notes() { return t('modal.notes'); },
	get notesPlaceholder() { return t('modal.notesPlaceholder'); },
	get createTask() { return t('modal.createTask'); },
	get firstDate() { return t('modal.firstDate'); },
	get endDateBound() { return t('modal.endDateBound'); },
	get projectEdit() { return t('modal.projectEdit'); },
	get projectNew() { return t('modal.projectNew'); },
	get projectName() { return t('modal.projectName'); },
	get projectType() { return t('modal.projectType'); },
	get projectColor() { return t('modal.projectColor'); },
	get projectDesc() { return t('modal.projectDesc'); },
	get projectDescPlaceholder() { return t('modal.projectDescPlaceholder'); },
	get projectStage() { return t('modal.projectStage'); },
	get createProject() { return t('modal.createProject'); },
	get oppName() { return t('modal.oppName'); },
	get oppStatus() { return t('modal.oppStatus'); },
	get oppTags() { return t('modal.oppTags'); },
	get oppTagsPlaceholder() { return t('modal.oppTagsPlaceholder'); },
	get oppNotes() { return t('modal.oppNotes'); },
	get oppNotesPlaceholder() { return t('modal.oppNotesPlaceholder'); },
	get oppLink() { return t('modal.oppLink'); },
	get oppLinkPlaceholder() { return t('modal.oppLinkPlaceholder'); },
	get oppGenLink() { return t('modal.oppGenLink'); },
	get oppStar() { return t('modal.oppStar'); },
	get oppCreate() { return t('modal.oppCreate'); },
	get oppEdit() { return t('modal.oppEdit'); },
	get bannerTitle() { return t('modal.bannerTitle'); },
	get bannerHint() { return t('modal.bannerHint'); },
	get bannerConfirm() { return t('modal.bannerConfirm'); },
	get weekdays() { return tArr('modal.weekdays'); },
	get weekdayShort() { return tArr('modal.weekdayShort'); },
	get weekdayLabel() { return tArr('modal.weekdayLabel'); },
	get prioUrgentImp() { return t('modal.prioUrgentImp'); },
	get prioImpNotUrgent() { return t('modal.prioImpNotUrgent'); },
	get prioUrgentNotImp() { return t('modal.prioUrgentNotImp'); },
	get prioNotImpNotUrgent() { return t('modal.prioNotImpNotUrgent'); },
	get stTodo() { return t('modal.stTodo'); },
	get stInProgress() { return t('modal.stInProgress'); },
	get stBlocked() { return t('modal.stBlocked'); },
	get stDone() { return t('modal.stDone'); },
	get stCancelled() { return t('modal.stCancelled'); },
	get typeNormal() { return t('modal.typeNormal'); },
	get typeRecurring() { return t('modal.typeRecurring'); },
	get freqChoose() { return t('modal.freqChoose'); },
	get freqDaily() { return t('modal.freqDaily'); },
	get freqWeekly() { return t('modal.freqWeekly'); },
	get freqMonthly() { return t('modal.freqMonthly'); },
	get remOnDay() { return t('modal.remOnDay'); },
	get rem1Day() { return t('modal.rem1Day'); },
	get rem3Day() { return t('modal.rem3Day'); },
	get rem1Week() { return t('modal.rem1Week'); },
	get editStatus() { return t('modal.editStatus'); },
	get editPriority() { return t('modal.editPriority'); },
	get editStart() { return t('modal.editStart'); },
	get editDue() { return t('modal.editDue'); },
	get editNotes() { return t('modal.editNotes'); },
	get editDeps() { return t('modal.editDeps'); },
	get depsEmpty() { return t('modal.depsEmpty'); },
	get depsCycle() { return t('modal.depsCycle'); },
	get dailyNode() { return t('modal.dailyNode'); },
	get todayDone() { return t('modal.todayDone'); },
	get todaySkip() { return t('modal.todaySkip'); },
	get todayNote() { return t('modal.todayNote'); },
	get noNote() { return t('modal.noNote'); },
	get overdueTag() { return t('modal.overdueTag'); },
	get cdTitle() { return t('modal.cdTitle'); },
	get cdEventName() { return t('modal.cdEventName'); },
	get cdTargetDate() { return t('modal.cdTargetDate'); },
	get cdEventPlaceholder() { return t('modal.cdEventPlaceholder'); },
	get cdHint() { return t('modal.cdHint'); },
	get cdAdd() { return t('modal.cdAdd'); },
	get cdMax() { return t('modal.cdMax'); },
	get cdEmpty() { return t('modal.cdEmpty'); },
	get cdDelete() { return t('modal.cdDelete'); },
	get cdDone() { return t('modal.cdDone'); },
	get opKanban() { return t('modal.opKanban'); },
	get opList() { return t('modal.opList'); },
	get opNew() { return t('modal.opNew'); },
	get opViewRight() { return t('modal.opViewRight'); },
	get opOpenLink() { return t('modal.opOpenLink'); },
	get opStatusPrefix() { return t('modal.opStatusPrefix'); },
	get opUnstar() { return t('modal.opUnstar'); },
	get opStar() { return t('modal.opStar'); },
	get opEmptyStage() { return t('modal.opEmptyStage'); },
	get opName() { return t('modal.opName'); },
	get opCreated() { return t('modal.opCreated'); },
	get opStarCol() { return t('modal.opStarCol'); },
	get opNoLink() { return t('modal.opNoLink'); },
	get opSaved() { return t('modal.opSaved'); },
	get opUpdated() { return t('modal.opUpdated'); },
	get opCreatedToast() { return t('modal.opCreatedToast'); },
	get opDeleted() { return t('modal.opDeleted'); },
	get opStatusUpdated() { return t('modal.opStatusUpdated'); },
	get opDetail() { return t('modal.opDetail'); },
	get opNamePh() { return t('modal.opNamePh'); },
	get opTagPh() { return t('modal.opTagPh'); },
	get opNotesPh() { return t('modal.opNotesPh'); },
	get opStagePh() { return t('modal.opStagePh'); },
	get opLinkPh() { return t('modal.opLinkPh'); },
	get opStarHint() { return t('modal.opStarHint'); },
	get poTaskMoved() { return t('modal.poTaskMoved'); },
	get poTaskFileMissing() { return t('modal.poTaskFileMissing'); },
	get poStatusFilter() { return t('modal.poStatusFilter'); },
	get poClearFilter() { return t('modal.poClearFilter'); },
	get poAlreadyInProject() { return t('modal.poAlreadyInProject'); },
	get poAlreadySubtask() { return t('modal.poAlreadySubtask'); },
	get poParentCycle() { return t('modal.poParentCycle'); },
	// 补齐 ProjectModal / TaskModal 残留硬编码
	get taskNamePlaceholder() { return t('modal.taskNamePlaceholder'); },
	get projectNamePlaceholder() { return t('modal.projectNamePlaceholder'); },
	get projectTypeStage() { return t('modal.projectTypeStage'); },
	get projectTypeNoStage() { return t('modal.projectTypeNoStage'); },
	get stagesDefault() { return tArr('modal.stagesDefault'); },
	// 补齐 OpportunityModal / ProjectBoard 残留硬编码
	get oppNamePlaceholder() { return t('modal.oppNamePlaceholder'); },
	get poScaleDay() { return t('ui.poScaleDay'); },
	get poScaleWeek() { return t('ui.poScaleWeek'); },
	get poScaleMonth() { return t('ui.poScaleMonth'); },
	get poScaleQuarter() { return t('ui.poScaleQuarter'); },
	get poDeleteTask() { return t('modal.poDeleteTask'); },
};
